### ISSUE TITLE
Error code msvcp140_atomic_wait.dll was not found 

### ISSUE THREAD

**Issue by Lalanava123** [fs-c/maniac#80] opened 2023-02-09 09:21 UTC
Error code msvcp140_atomic_wait.dll was not found

**Comment by fs-c** [comment] 2023-02-10 16:37
Make sure you have a recent version of the MSVC redist installed.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Jazperez-c** [comment] 2023-02-11 09:13
oh Im already have MSVCP140_ATOMIC_WAIT.dll and try to reinstall visual cc+ again but I cant to open maniac same too.

**Comment by fs-c** [comment] 2023-02-11 10:31
I can't reproduce the issue, either on my system or on a clean VM, and I'm not sure what would cause this. I'll look into it some more.

If you manage to solve this in the meantime, please let me know how you did it.

**Comment by Jazperez-c** [comment] 2023-02-11 15:03
[image: messageImage_1676127646336.jpg][image:
messageImage_1676127705653.jpg]

This can make it clear to you that
How is that problem?


ในวันที่ ส. 11 ก.พ. 2023 เวลา 17:31 lw ***@***.***> เขียนว่า:

**Comment by fs-c** [comment] 2023-02-11 15:09
@Jazperez-c I can't see the image that you were trying to send. Either send me a link or attach it to the comment via the GitHub interface (not as an email attachment).

**Comment by Jazperez-c** [comment] 2023-02-11 15:12
![messageImage_1676127646336](https://user-images.githubusercontent.com/125122270/218266055-36e6b250-a21a-478f-981c-f5f6e1dc066c.jpg)
![messageImage_1676127705653](https://user-images.githubusercontent.com/125122270/218266057-6c6e3aab-4f6c-4aff-a347-dc95d825b390.jpg)

**Comment by fs-c** [comment] 2023-02-11 15:15
@Jazperez-c I see what the problem is, but I don't know why the DLL can't be found. Can you try copying the DLL to the folder maniac.exe is in?

**Comment by Jazperez-c** [comment] 2023-02-11 15:25
![messageImage_1676128957682](https://user-images.githubusercontent.com/125122270/218266538-6769992d-add3-46a6-94c8-bddc148a974b.jpg)
![messageImage_1676128816665](https://user-images.githubusercontent.com/125122270/218266540-88dd6611-7bfb-4648-9e2f-76fdd8950618.jpg)

Now I have solved the problem of the dll part gone ิy downloading Visual C++ all versions, but the additional problem is failed to reading memory.

**Comment by fs-c** [comment] 2023-02-11 15:27
So you installed all versions of the MSVC runtime? The memory reading error is probably because osu! hasn't loaded the relevant parts yet, should be fixed by starting a map and then quitting again.

**Comment by Jazperez-c** [comment] 2023-02-11 15:27
Fix MSVCP140_ATOMMIC_WAIT.dll was not found
download this and install all .

: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

now i found a new problem is in previous message

**Comment by Jazperez-c** [comment] 2023-02-11 15:28
OK i will try

**Comment by Jazperez-c** [comment] 2023-02-11 15:29
It's worked !! Thank you for your help!!

**Comment by Jazperez-c** [comment] 2023-02-11 15:30
> So you installed all versions of the MSVC runtime? The memory reading error is probably because osu! hasn't loaded the relevant parts yet, should be fixed by starting a map and then quitting again.

yes install alll version

**Closed** 2023-03-02 13:53 UTC
