### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mahuyre** [fs-c/maniac#83] opened 2023-04-01 07:01 UTC
Whenever I open it and go into a beatmap it says found beatmap but won't change it to playing status, I tried to use the debug menu and when I went into a beatmap there were lot's of error messages saying it couldn't find the map

**Comment by SteezySaturn** [comment] 2023-04-01 07:27
its broken

**Comment by mahuyre** [comment] 2023-04-01 07:32
🤯🤯🤯🤯🤯🤯

**Comment by fs-c** [comment] 2023-04-04 16:36
Duplicate of #82

**Closed by fs-c** 2023-04-04 16:36 UTC
